name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_DEV_DEBUG: line-tables-only

jobs:
  lint:
    name: Format and Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - &toolchain
        id: toolchain
        run: rustup toolchain install && echo "rustc=$(rustc --version | cut -d' ' -f2)" >> "$GITHUB_OUTPUT"
      - &cache
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            target
          key: ${{ runner.os }}-${{ github.job }}-rustc-${{ steps.toolchain.outputs.rustc }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: ${{ runner.os }}-${{ github.job }}-rustc-${{ steps.toolchain.outputs.rustc }}-
      - run: cargo fmt --all --check
      - run: cargo clippy --locked --all-targets -- -D warnings

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - *toolchain
      - *cache
      - run: cargo test --locked --lib --bins
      - run: cargo test --locked --test dynamodb_local
